# whoami.yml
# Dynamische Konfiguration für Whoami

# http routing section
http:
  routers:
    # Define a connection between requests and services
    to-whoami:
      rule: "PathPrefix(`/whoami/`)"
      # If the rule matches, forward to the whoami service (declared below)
      service: whoami

  services:
    # Define how to reach an existing service on our infrastructure
    whoami:
      loadBalancer:
        servers:
        - url: http://localhost:9000



# TCP routing section
tcp:
  routers:
    to-whoami-tcp:
      rule: "HostSNI(`*`)"
      service: whoami-tcp
      entryPoints:
        - tcp-whoami

  services:
    whoami-tcp:
      loadBalancer:
        servers:
          - address: "localhost:9000"